import { BlogPost } from '@/types'

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    slug: 'ai-lead-generation-small-business-2024',
    title: 'How AI Lead Generation is Transforming Small Businesses in 2024',
    excerpt:
      'Discover how small businesses are leveraging AI to automate lead capture, qualify prospects, and book appointments — without a full sales team.',
    content: `## The New Era of Lead Generation\n\nFor decades, small businesses relied on cold calls, word-of-mouth, and expensive ad campaigns to generate leads. The process was manual, time-consuming, and inconsistent. Now, artificial intelligence is changing everything.\n\n## What AI Lead Generation Actually Means\n\nAI lead generation isn't just about automation — it's about intelligence. Modern AI systems can...\n\n## The ROI for Small Businesses\n\nBusinesses using AI lead gen see on average a 3x increase in qualified leads and 40% reduction in cost-per-acquisition.`,
    cover_image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80',
    author: 'Marcus Chen',
    category: 'AI & Automation',
    tags: ['AI', 'Lead Generation', 'Small Business', 'Automation'],
    published: true,
    published_at: '2024-05-15T10:00:00Z',
    reading_time: 7,
  },
  {
    id: '2',
    slug: 'automated-follow-up-sequences-guide',
    title: 'The Ultimate Guide to Automated Follow-Up Sequences That Convert',
    excerpt:
      'Most leads need 5-8 touchpoints before converting. Here\'s how to build automated sequences that nurture leads while you sleep.',
    content: `## Why Follow-Up Sequences Matter\n\nStudies show that 80% of sales require at least 5 follow-up contacts, yet 44% of salespeople give up after just one. Automation solves this gap.\n\n## Building Your Sequence\n\nA high-converting sequence typically follows this structure...`,
    cover_image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=1200&q=80',
    author: 'Sarah Williams',
    category: 'Sales Strategy',
    tags: ['Email Marketing', 'Automation', 'Sales', 'CRM'],
    published: true,
    published_at: '2024-05-08T10:00:00Z',
    reading_time: 9,
  },
  {
    id: '3',
    slug: 'ai-qualification-scoring-leads',
    title: 'AI Lead Scoring: How to Automatically Qualify Your Best Prospects',
    excerpt:
      'Stop wasting time on unqualified leads. Learn how AI scoring models can predict which prospects are most likely to convert.',
    content: `## The Problem with Manual Qualification\n\nSales teams spend up to 50% of their time chasing leads that will never convert. AI qualification scoring fixes this.\n\n## How AI Scoring Works\n\nModern AI models analyze dozens of signals...`,
    cover_image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80',
    author: 'Alex Rodriguez',
    category: 'AI & Automation',
    tags: ['AI', 'Lead Scoring', 'CRM', 'Sales Intelligence'],
    published: true,
    published_at: '2024-04-28T10:00:00Z',
    reading_time: 6,
  },
  {
    id: '4',
    slug: 'appointment-booking-automation-guide',
    title: 'Automate Your Appointment Booking: A Step-by-Step Implementation Guide',
    excerpt:
      'Eliminating the back-and-forth of scheduling is one of the highest-ROI automations any service business can implement.',
    content: `## The Cost of Manual Scheduling\n\nThe average scheduling interaction takes 8 emails and 4 days. AI-powered booking eliminates all of that.\n\n## Implementation Steps\n\nHere's how to set up a fully automated booking system...`,
    cover_image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=1200&q=80',
    author: 'Jordan Park',
    category: 'Productivity',
    tags: ['Scheduling', 'Automation', 'Productivity', 'CRM'],
    published: true,
    published_at: '2024-04-15T10:00:00Z',
    reading_time: 8,
  },
  {
    id: '5',
    slug: 'saas-marketing-automation-stack-2024',
    title: 'Building the Perfect Marketing Automation Stack for Your SaaS in 2024',
    excerpt:
      'The tools and workflows that top-performing SaaS companies use to automate their entire customer acquisition funnel.',
    content: `## Choosing Your Stack\n\nThe right marketing automation stack depends on your stage, budget, and goals. Here's a breakdown by company stage...`,
    cover_image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
    author: 'Emma Thompson',
    category: 'Marketing',
    tags: ['SaaS', 'Marketing Automation', 'Growth', 'Tools'],
    published: true,
    published_at: '2024-04-02T10:00:00Z',
    reading_time: 11,
  },
  {
    id: '6',
    slug: 'conversational-ai-chatbots-lead-capture',
    title: 'Conversational AI: Using Chatbots to Capture and Qualify Leads 24/7',
    excerpt:
      'Your website visitors want answers immediately. AI chatbots can engage, qualify, and capture leads around the clock.',
    content: `## Why Conversational AI Works\n\nAI chatbots respond in milliseconds. Studies show that responding to a lead within 5 minutes increases conversion rates by 9x.\n\n## Building Your AI Chatbot Flow\n\nA high-performing chatbot follows a specific conversation structure...`,
    cover_image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=1200&q=80',
    author: 'Daniel Kim',
    category: 'AI & Automation',
    tags: ['Chatbots', 'AI', 'Lead Generation', 'Conversion'],
    published: true,
    published_at: '2024-03-20T10:00:00Z',
    reading_time: 7,
  },
]
